spring:
  application:
    name: application-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: app
    password: app
    url: jdbc:postgresql://localhost:5432/test_app

server:
  port: 8100

eureka:
  instance:
    hostname: localhost
