spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

server:
  port: 80

eureka:
  instance:
    hostname: localhost